Testing
YunoHost-Apps/plume_ynh pull request #63
Opened 2021-01-07 20:06 UTC by yalh76

## Problem
- *Fix #61*
- *Fix #22*

## Solution
- *Upgrade to 0.6.0~ynh1*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
[![Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/plume_ynh%20PR63%20(yalh76)/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/plume_ynh%20PR62%20(yalh76)/)

2021-01-11 12:30 UTC, igalic reviewed
🙋🏻‍♀️

2021-01-11 12:30 UTC, igalic commented on conf/.env
> +
do you folks use ldap?

2021-01-11 12:32 UTC, igalic requested changes

2021-01-11 12:32 UTC, igalic commented on manifest.json
>      "url": "https://baptiste.gelez.xyz/",
this url should be https://joinplu.me/

2021-01-19 22:00 UTC, yalh76 commented on conf/.env
> +
yes, we are using openldap

2021-01-19 22:02 UTC, yalh76 commented on manifest.json
>      "url": "https://baptiste.gelez.xyz/",
fixed ^^

2021-01-19 22:02 UTC, yalh76 commented
Having some trouble to build the arm64 version ... So waiting to build it before releasing

2021-01-19 22:34 UTC, yalh76 commented
!testme

2021-01-22 18:41 UTC, ericgaspar approved these changes

2021-02-01 15:42 UTC, alexAubin approved these changes
LGTM

2021-02-18 23:20 UTC, alexAubin commented
Lets uuuuuuuh meeeerge then :eyes: ?

2021-02-23 02:10 UTC, yalh76 commented
> 
> 
> Lets uuuuuuuh meeeerge then 👀 ?

was waiting to be abble to build arm64 version....
But now it's ready ^^

2021-02-23 02:10 UTC, merged